### ISSUE TITLE
No dropped message support

### ISSUE THREAD

**Issue by nift4** [pigamedrv/pitft_touchscreen#6]
@BroMarduk Can you merge that also into here?

**Comment by BroMarduk** [comment]
The dropped message support is already in the resistive-support branch.    I would recommend syncing your master with the current PrzemoF/pitft_touchscreen master branch.   It would also get your fork in sync with the main one and I believe it's feature identical now as I backfilled the evdev check.

I've been on a work trip for the past week, but will be back tomorrow.

**Comment by nift4** [comment]
Merging skills...

**Comment by nift4** [comment]
Finished.

**Comment by BroMarduk** [comment]
Looks good.
